spring.application.name=taskStudent

spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=postgres
spring.datasource.password=akhi-8008

spring.jpa.hibernate.ddl-auto=update
